### PR TITLE
Default kubevirt version set to `sprint5`

### PR DESCRIPTION
**Pull request by mareklibra**
Follow-up for https://github.com/ansibleplaybookbundle/kubevirt-apb/pull/13

### CODE REVIEW

**Comment by karmab** [comment]
dockerfile also need to be updated

**Comment by mareklibra** [comment]
done

**Comment by karmab** [comment]
lets wait for sprint demo to be done before merging

**Comment by rthallisey** [comment]
@mareklibra do you need this for the sprint demo?

**Comment by rthallisey** [comment]
missed your comment @karmab, ack

**Comment by karmab** [comment]
its not needed for sprint demo, as one can specify which release to use when deploying anyway

**Comment by mareklibra** [comment]
right, just a matter of convenience

**Pull request merged**
