### PR TITLE
Adding CI

### PR DESCRIPTION
**Pull request by gbenhaim**
- When sending a PR, check patch will be triggered. This script
  should build and test the APB (The test isn't implemented yet).

- When the PR is merged, check-merged will be triggered. This script
  builds and publish the APB at https://hub.docker.com/u/ovirtinfra/

- The APB will have a label called "git-sha", which contains the sha of
  the commit that was used to build the APB.

Signed-off-by: gbenhaim <galbh2@gmail.com>

### CODE REVIEW

**Comment by gbenhaim** [comment]
ci test please

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by gbenhaim** [comment]
ci add to whitelist

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci test please

**Comment by gbenhaim** [comment]
ci add to whitelist

**Comment by gbenhaim** [comment]
ci add to whitelist

**Comment by gbenhaim** [comment]
@rthallisey I'm searching for the best way to test the APB.
I saw that the broker's CI doesn't test on Openshift 3.10 (one of the commits messages says that the automation for OC 3.10 is broken, not sure if it's because of the broker or OC).

I think that merging this PR is a good start because it will publish the APB to docker hub on each merge (The APB will be published to  https://hub.docker.com/u/ovirtinfra/).

**Comment by rthallisey** [comment]
@gbenhaim I have automated builds setup in ansibleplaybookbundle/kubevirt-apb that will rebuild with the latest tag after a PR is merged. 

> @rthallisey I'm searching for the best way to test the APB.
>
We can catch up in Tel Aviv next week.

**Comment by rthallisey** [comment]
@gbenhaim let's hold on this for now until post tel aviv.

**Comment by gbenhaim** [comment]
Sure, good to hear that you are coming next week!

**Pull request merged**
